### ISSUE TITLE
What if I am using a pre-installed 3rd party app and want to mock the network requests being made by it ?

### ISSUE THREAD

**Issue by ponienchen** [laevandus/UITestingNetworking#1]
Thanks for such detailed approach to mocking network requests for the app whose source codes are located locally.

In my situation, I would like to test a pre-installed 3rd party app, and then intercept the network requests it makes and stub the responses for specific paths.

Is that doable using the same approach ?

Thank you!

**Comment by laevandus** [comment]
This techique is only usable if you can modify the source code of the app. Sounds like that you would need some sort of proxy approach instead.

**Comment by ponienchen** [comment]
ah....too bad.

Thank you for your response!
Really appreciated that.
